- src/Common/Handlers/NewEnvironmentHandler.cs
ChangeSet was being reused between versions. This was ok before maintaining the CustomerEnvironments in state Created because it was being terminated after each approval.
> fix(): changeset not being implicit for new versions

- .github/workflows/npm-publish.yml
- npm/install.js
- npm/package.json
- src/Console/Console.csproj
- src/Version.props
- Console tool renamed from `cmf-portal-sdk` to `cmf-sdk`.
- Added package.json to allow NPM package creation. This will, on the package installation, download the correct release binaries and extract them, so them can be accessible by the CMF CLI.
- Created a github workflow that, when a release is created, automatically compiles the release assets, and publishes the new package to npmjs.com
> SDK console tool renamed. NPM package automatically published on release creation.

- src/Common/Resources.cs
- src/Console/CheckAgentConnectionCommand.cs
- src/Console/CreateInfrastructureCommand.cs
- src/Console/CreateInfrastructureFromTemplateCommand.cs
- src/Console/DeployAgentCommand.cs
- src/Console/DeployCommand.cs
- src/Console/DeployParameters.cs
- src/Console/Extensions/CommonParametersExtension.cs
- src/Console/Program.cs
- src/Powershell/Extensions/CommonParametersExtension.cs
- src/Version.props
**Changes**
- The System.CommandLine library has a logic that creates an alias every time it receives --name as an argument and it is not possible to have an alias with spaces. To work around this issue, --name was changed to --id and a condition was added to continue allowing the user to pass --name as an argument.
- An issue was created in Command Line api github repository (https://github.com/dotnet/command-line-api/issues/1705)
> 72705 - Portal SDK fails when installing a customer environment with spaces on the name

- src/Common/Services/EnvironmentDeploymentHandler.cs
**Changes**
- Remove spaces and " from directory.
> 72705 - Portal SDK fails when installing a customer environment with spaces on the name - Reactivation

- src/Common/Handlers/NewInfrastructureFromTemplateHandler.cs
- src/Common/Handlers/NewInfrastructureHandler.cs
- src/Common/Resources.cs
- src/Console/CreateInfrastructureCommand.cs
- src/Console/CreateInfrastructureFromTemplateCommand.cs
- src/Powershell/NewInfrastructure.cs
- src/Powershell/NewInfrastructureFromTemplate.cs
CustomerInfrastructure's InfrastructureAgent can no longer be previously created and assigned by name during CustomerInfrastructure creation or edition. It must be a two-step operation: the CustomerInfrastructure must be created without InfrastructureAgent, and then the InfrastructureAgent is created assigned to the existing CustomerInfrastructure.
> CustomerInfrastructure's InfrastructureAgent is no longer choosable during CustomerInfrastructure creation

- src/Common/CustomerPortalClient.cs
- src/Common/ICustomerPortalClient.cs
- src/Common/Services/InfrastructureCreationService.cs
**Changes**
- Check if infrastructure exists by id instead of by name.
- Check if infrastructure owner role is created after creating the infra. In case the role does not exist, an active wait is added.
> 83557 - Portal SDK fails when deploying the agent when creating new Infrastructure and Agents entities

- src/Common/Services/InfrastructureCreationService.cs
- src/Version.props
**Changes**
- Change levelsToLoad in GetObjectByName when loading an infrastructure because with levelsToLoad equal to 0 the client is not loaded.
> 8500 - portal-sdk does not load all necessary information in infrastructure when it already exists

- src/Common/CustomerPortalClient.cs
- src/Common/ICustomerPortalClient.cs
- src/Version.props
**Changes**
- Fix terminate other versions. With no operation target, TerminateObjects service terminates objects at the revision level by default.
> 74130 - Fix terminate other versions

- .github/workflows/npm-publish.yml
- npm/install.js
Changed git hub release action to provide the release tag to the install.js script, in order for it to download the artifact from the correct url.
> fix(): use release tag in install.js script instead of app version

- .github/workflows/build.yml
- src/Common/Common.csproj
- src/Common/Services/Utilities.cs
- src/Console/Console.csproj
- src/Console/Properties/launchSettings.json
- src/Powershell/Powershell.csproj
* Upgrades the version of .net to .net 8 in all projects of the solution.
* Alters the build to fetch the artifacts from the different path
* Manually validated by running:
1. cmf-portal login
2. cmf-portal checkagentconnection
> feat(): upgrade portal sdk to use .net 8 #98231

- .vscode/launch.json
- README.md
- src/Common/CmfPortalSession.cs
- src/Common/ISession.cs
* Support reading the CM Portal token from an environment variable "CM_PORTAL_TOKEN".
* If the environment variable has a non-empty and non-whitespace value, it is cached in memory only and not in file. It will be used for requests to the CM Portal.
* Otherwise, the application behaves as if no token exists and each command that requires a valid login will throw an error if the login wasn't performed.
**Note**: If the login command is run, the environment variable is not taken into account since this command is used to explicitly save the token passed as an option or fetched from the interactive login. In this case, the token is still cached to a file as it was.
> feat(): Read cm portal token from env var

- .github/workflows/npm-publish.yml
- src/Version.props
* Updated the npm-publish github workflow to target net8.
* Version bump to 1.13.9
> fix(): Release workflow not supporting net8 and missing version bump

- npm/install.js
- src/Version.props
In linux, after the install.js is run, the extracted release does not have execute permissions on the cmf-portal binary, preventing its usage.
1. When extracting the zip file, prevent the extract process from changing the original permissions of the content. It was noted that, when the release was built, the binary had `rwx` perms, which means that we just need to maintain those.
2. Fixed an issue, in case of an error when downloading the release package, that the error variable `error` was being used as `e`, causing a syntax error.
> fix(): keep original permissions when extracting the zip

- src/Common/Services/NewEnvironmentUtilities.cs
- src/Version.props
Prevent the portal-sdk from getting CustomerEnvironments that are in Status TerminationFailed (and UniversalState Created) to be terminated. TerminationFailed environments should always be in UniversalState Terminated state as well and, if that isn't the case, they should remain in that inconsistent status so that we can investigate the issue behind it.
* Removed TerminationFailed from DeploymentStatus Query Filter
> fix(): prevent TerminationFailed environments to be terminated

- src/Common/Utils.cs
- src/Version.props
Fixed GetLicenseByUniqueName for PowerShell environment.
Also throws exception if license is not found.
> Fixed GetLicenseByUniqueName for PowerShell environment

- src/Common/CmfPortalSession.cs
- src/Version.props
This PR solves the scenario (for now only seen in linux) when the ApplicationData folder doesn't exists:
before:
after:
> chore: create ApplicationData folder if not exists

- npm/install.js
- npm/package.json
- src/Version.props
The request to download the portal-sdk binary, through `axios`, is not working. It **may** be related with this [issue](https://github.com/axios/axios/issues/4533).
A work-around that seems to work is to send the `httpAgent` and `httpsAgent` ourselves, through the `proxy-agent` (which is the one that axios also uses) and disabling its internal proxy configuration.
This was validated in a Microshift VM, through a proxy.
Test on a pwsh window with proxy:
> fix(): portal-sdk binary download not working through a proxy

- npm/package.json
- src/Version.props
Downgraded the required `proxy-agent` dependency from `^6.5.0` to `^5.0.0` to support Node 12.
Unfortunately, it includes some vulnerabilities but there's no way to fix since there are packages dependencies mismatches. However, this is only required for 2 more months, which is the end-of-life for MES v8 LTS.
Tests:
With current package.json and node 12.22.12:
With newer package.json and node 12.22.12:
> fix(): Downgrade proxy agent version to support node 12

- src/Common/Handlers/NewEnvironmentHandler.cs
Instead of filling the "DeploymentPackage" and the "SoftwareLicense", send that data as a "Relation" in the requests.
Create a customer environment using the PortalSDK
Create a customer environment in a infrastructure using PortalSDK
Create a new version of a customer environment using PortalSDK
Other relevant tests
> Create environment and send DP and Licence as relation

- .github/workflows/build.yml
- .github/workflows/npm-publish.yml
- README.md
> Add run unit tests in pipeline
